### ISSUE TITLE
README - CurrencyFormatter is not valid helper (currently)

### ISSUE THREAD

**Issue by tomkadwill** [lotus/helpers#13]
The README examples use `CurrencyFormatter`: https://github.com/lotus/helpers/blob/master/README.md#bad-style-example

This is not as valid helper AFAIK. Should this be changed to a helper that is actually implemented? As it may confuse users.

**Comment by jodosha** [comment]
@tomkadwill Feel free to change it with your upcoming `NumberFormatter` example.

**Comment by jodosha** [comment]
Resolved by #11
