### ISSUE TITLE
Support HTML5 required constraint for text_field

### ISSUE THREAD

**Issue by joneslee85** [lotus/helpers#23]
Now:

```
text_field :my_field, required: true
```
generates

```
<input type="text" required="true">
```

which is *invalid* HTML5 syntax

It should generate this instead:

```
<input type="text" required>
```

**Comment by pascalbetz** [comment]
@joneslee85 i'll look into it.

**Comment by jodosha** [comment]
Both `required="true"` and `required` are correct. The latter is a nice shortcut that HTML5 browsers support.

Quoting W3C SPEC:

> Empty attribute syntax
> Certain attributes may be specified by providing just the attribute name, with no value.

> In the following example, the disabled attribute is given with the empty attribute syntax:

> `<input disabled>`

> Note that empty attribute syntax is exactly equivalent to specifying the empty string as the value for the attribute, as in the following example.

> `<input disabled="">`

http://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty

**Comment by jodosha** [comment]
There is another issue with this approach. We want to make `required` a special attribute that no requires quoted value, but if we want to follow the same path, we should render all the other attributes with the same syntax. Think of `disabled` or `checked`.

But because this will increase the internal complexity and so the rendering process, I'm keen to leave things as they are, because the actual implementation produces a valid markup.

**Comment by pascalbetz** [comment]
If a boolean attribute is present, then no matter what its value is, the browser will interprete it as set:

https://jsfiddle.net/jgvjtr93/1/

So the caller would need to make sure that he actually omits the attribute completely instead of passing it with _false_ as value:
```ruby
attributes = {style: 'some css here'}
attributes[:disabled] = "disabled" if disabled?
```
instead of:
```ruby
attributes = {style: 'some css here', diabled: disabled?}
```

**Comment by jodosha** [comment]
@pascalbetz Your observation is correct. Would you like to fix that? Thank you.

**Comment by pascalbetz** [comment]
@jodosha 

Will do.

**Comment by joneslee85** [comment]
@jodosha the `required="true"` is not valid, according to W3C spec

```
The values "true" and "false" are not allowed on boolean attributes. To represent a false value, the attribute has to be omitted altogether.
```

Refer to: http://www.w3.org/html/wg/drafts/html/master/infrastructure.html#boolean-attribute

Though not a fan of valueless attribute, I still want to provide an intuitive DSL `required: true` which generates `required="required"`

**Comment by pascalbetz** [comment]
@joneslee85 this is the way i'm going because it is still valid XML syntax. Any boolean attribute that has a trueish value will be added with 

```attribute_name="attribute_name"```
This keeps the code simple.

**Comment by joneslee85** [comment]
@pascalbetz go for it
