### ISSUE TITLE
integration/router_helper_test.rb failing

### ISSUE THREAD

**Issue by skinofstars** [lotus/helpers#24]
```
1) Failure:
Routing helper#test_0001_uses helper [/Users/pascal/repositories/lotus/lotus-helpers/test/integration/routing_helper_test.rb:9]:
--- expected
+++ actual
@@ -1 +1,2 @@
-"/dashboard"
+"/dashboard\r
+"
```

Confirmed on Vagrant using ubuntu 14.04 and ruby 2.2
Also on OS X 10.10.4, Ruby 2.2.0 by @pascalbetz

CI seems fine

**Comment by pascalbetz** [comment]
Problem is line ending.

If template ends with "0D 0A" then the test fails. If it ends with "0A" then it succeeds. Not sure what the expected output is but i guess the test is not entirely correct. If this is the case:
Either check for "contains", add the line ending to the test or chomp before compare.

**Comment by pascalbetz** [comment]
@skinofstars @joneslee85 

I found out why that test failed on my machine (and not on the others). It's a config issue for git. I think my fix is not required (even though it did not break something... the test is now less exact as it only checks for inclusion).


Problem was (and i have no clue how this got into my config): 

```bash
[core]
	autocrlf = true
```

where as it should be 

```bash
[core]
	autocrlf = input
```

@skinofstars: can you please check that setting in your ~/.gitconfig?

**Comment by joneslee85** [comment]
@pascalbetz good find, if so, we could revert the changes

**Comment by pascalbetz** [comment]
@joneslee85 yes... let's wait what @skinofstars reports back.

**Comment by skinofstars** [comment]
@pascalbetz @joneslee85 hmm, I don't have that setting in my ~/.gitconfig. It looks like `autocrlf = input` is for auto-fixing*. I take it you added that Pascal? 

I'm not sure you can expect everyone to have that configured, so it might be better to do the less exact check.

* https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace

**Comment by pascalbetz** [comment]
Yes, i added it. For whatever reason it was set to "true" before.

On *nix systems line endings should be LF, not CRLF. So i think it's OK to assume this, and to fix it (converting CRLF to LF) if it should be broken. At least not set it to true.
