### ISSUE TITLE
Support for text nodes

### ISSUE THREAD

**Issue by josemota** [lotus/helpers#29]
I was making my way towards building a form using the HTML5 API. However, it seems to be that it's currently impossible to accomplish the following:

```html
<p>
  <label>
    Your name?
    <input type="text" name="object[name]" />
  </label>
</p>
```

A possible solution could be something like:

```ruby
# ...
p do
  label do
    text "Your name?"
    text_field :name
  end
end
```

What do you guys think?

**Comment by joneslee85** [comment]
I like the idea

cc @AlfonsoUceda @jodosha

**Comment by josemota** [comment]
@joneslee85 referred to the possibility for injection to happen. I'll add a failing test to start and work a solution out.
