### ISSUE TITLE
Number formatting

### ISSUE THREAD

**Issue by jodosha** [lotus/helpers#3]
Introduce a module that provides formatting facilities for numbers.
It should accept any kind of number and return a comma delimited string, with decimal separator.

Please consider to include both unit and integration tests. Please have a look at `lotus-assets` for integration tests example.

The goal is to provide private methods (if possible). This should forbid bad usage of those helpers:

```erb
<%= format_number cart.total %>
```

The aimed style is to let templates to bind only one expression.

```erb
<%= total %>
```

Where `#total` is defined like this:

```ruby
class MyView
  include Lotus::Helpers::Numbers

  def initialize(cart)
    @cart = cart
  end

  def total
    format_number @cart.total
  end
end
```

**Comment by tomkadwill** [comment]
I'll take a look at this, I'll submit a PR soon for review

**Comment by tomkadwill** [comment]
@jodosha @joneslee85 I've added a PR for this. It is still a WIP but I wanted to get your feedback as to whether it meets the requirement. Let me know whether anything needs changing.
