### ISSUE TITLE
`text_area` method is not providing either `id` or `name` attributes

### ISSUE THREAD

**Issue by josemota** [lotus/helpers#32]
The title is self-explanatory but here's my own example:

**Code**

```ruby
form_for :event, "/events", class: "row" do
  text_area :notes, placeholder: "Some text here.", class: "form-control", rows: 6
end
```

**Output**

```html
<form action="/events" method="post" class="row" id="event-form">
  <textarea rows="6" class="form-control" placeholder="Some text here"></textarea>
</form>
```

It is expected that the textarea has:

* A `name` attribute with the value of `event[notes]`;
* An `id` attribute with the value of `event-note`.

* * *

EDIT: The root cause of the bug is the inability to store both name and id when no content is passed in. Check [the discourse](https://github.com/lotus/helpers/issues/32#issuecomment-135385365)

**Comment by joneslee85** [comment]
Good find, would you be able to submit a PR? TIA

**Comment by pascalbetz** [comment]
Without looking into the code, shouldn't it be:

```ruby
form_for :event, "/events", class: "row" do |f|
  f.text_area :notes, placeholder: "Some text here.", class: "form-control", rows: 6
end
```
(Form builder passed as a block argument).

**Comment by joneslee85** [comment]
@pascalbetz nope

eg:
```
form_for :book, routes.books_path do
    text_field :title

    submit 'Create'
  end
```

**Comment by josemota** [comment]
@joneslee85 yes, absolutely. You'll need to give me some time, though. My wife is in the hospital, it seems that my baby wants to be born any hour now. :) I'll be in touch.

**Comment by AlfonsoUceda** [comment]
@joneslee85 you are right, it should be like the example https://github.com/lotus/helpers#view-usage

**Comment by pascalbetz** [comment]
@joneslee85  i was referring to the first example at http://lotusrb.org/guides/helpers/forms/ but without checking the text below. Argh.

@josemota : all the best!

**Comment by josemota** [comment]
@joneslee85 @pascalbetz My baby's been born! She's growing steadily now in the incubator for some time. Until then, I'll be on the lookout but I'll try and squeeze in some time to work something out.

Please bear with me :)

**Comment by josemota** [comment]
I've found the cause of this bug. It seems that not passing any content to the method will simply not register either `name` or `id`.

```ruby
text_area :notes, "forced content", rows: 1 # expected behavior is met
text_area :notes, rows: 1 # expected behavior is NOT met
```

I recall there's a place in the code where both of these are handled so I'll dig deeper. I'll edit the initial message with this mention for better contextualization.
