### ISSUE TITLE
titleize for label produces capitalized words in multi-word symbol or string

### ISSUE THREAD

**Issue by sebastjan-hribar** [lotus/helpers#34]
As I've stated in the name I get capitalized words in multi-word symbol or string in a form.

Example: :test_case produces Test Case in the view.
I'd like it to be Test case

In the form_builder.rb the label method uses the titleize method on the content which gives the result above.

Is there a way to work around this?

I'm thinking of something like:

```ruby
def convert(symbol)
    symbol = symbol.to_s
    if symbol.include?("_")
        symbol.sub!("_", " ").capitalize
    else
        symbol.capitalize
    end
end
```
It would work also for strings.
regards,
seba

**Comment by jodosha** [comment]
@sebastjan-hribar Thanks for this suggestion. A quick research revealed that it's a common pattern to capitalize and not to titleize form labels (Eg. "Confirm password" and not "Confirm Password").

I'd say to change the behavior here (see https://github.com/lotus/utils/pull/85). @lotus/core-team Thoughts?

**Comment by sebastjan-hribar** [comment]
@jodosha I had a look at the capitalize in lotus/utils#85 as you suggested and that would be great.
regards, seba
