### ISSUE TITLE
Add a number_field helper

### ISSUE THREAD

**Issue by awochna** [lotus/helpers#35]
So that my bookshelf application can say:

```ruby
div class: 'input' do
  label :percent_read
  number_field :percent_read
end
```

And I can show off how far I am through various books.

Alternatively, some extra sugar would be nice:

```ruby
div class: 'input' do
  label :percent_read
  number_field :percent_read, in: 0..100, step: 5
end
```

So that I can easily update how far I am in the book using 5% increments, but I can't go over 100% (extra credit?) or under 0% (lots and lots of slacking).

**Comment by jodosha** [comment]
@awochna I like it. :+1:

**Comment by awochna** [comment]
Great, I'll start working on a PR next week!
